# Generated by Django 3.0.5 on 2021-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEUAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='energy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
