# Generated by Django 3.0.5 on 2021-02-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEUAPI', '0002_power_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='meter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='power_meter', to='SEUAPI.Meter'),
            preserve_default=False,
        ),
    ]
